[project]
name = "llm-data-pipeline"
version = "0.1.0"
description = "ETL Pipeline for LLM Data Preparation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "polars",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "N"]
fix = true
