[project]
name = "llm-data-pipeline"
version = "0.1.0"
description = "ETL Pipeline for LLM Data Preparation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "polars",
    "pyspark>=3.5.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
line-length = 80
indent-width = 4
